name: cd

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: boblin1006
          password: f06c36b7-1e50-44d4-a8ab-9fe7769b3737
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: boblin1006/test0610:latest
